spring:
  application:
    name: demoWebApp

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

s3:
  user: user
  secret: pass
  bucket-name: titastextractbucket

scheduled:
  listS3Buckets: "0 0 * * * *"
  uploadJsonToS3: "*/7 * * * * *"
  getJsonFromS3: "*/10 * * * * *"